try:
    1/0
except Exception as X:
    print(X)

Saveit = X
# print(X)
print(Saveit)